import "~/styles/globals.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

import { SessionProvider } from "next-auth/react";
import { cn } from "~/lib/utils";
import { manrope } from "~/fonts";
import Footer from "~/components/Footer/Footer";
import Navbar from "~/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn(`${manrope.className}`)}>
      <body className='flex flex-col min-h-screen'>
        <SessionProvider>
          <Navbar />
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
